### ISSUE TITLE
Nautilus closes when I type from keyboard

### ISSUE THREAD

**Issue by vathe83** [jaybosamiya/nautilus-interactive-typeahead-debian#5] opened 2020-06-21 15:24 UTC
I have followed the installation steps, in Debian 10,  but when I open a nautilus window and start typing some letters, instead of selecting the Folder, the name of which matches my typing, it closes the Nautilus windows.

**Comment by jaybosamiya** [comment] 2020-06-21 15:39
Did you "Enable interactive search" in the Preferences menu, and then force kill nautilus (using `nautilus -q`)? Those are the two reasons I can think of. Other than that, I am not sure why it fails. One weird behavior I have seen is that sometimes it may require waiting for a few seconds before it actually stabilizes (no idea why it does that, but in such a scenario, I just `nautilus -q` to kill it, start it again, and then wait a few seconds before continuing). Hope that helps! Otherwise unfortunately, I don't know what is wrong, because I am on Debian 10 and it works for me, so it is likely something with respect to how it is set up.

**Comment by vathe83** [comment] 2020-06-22 14:13
I had indeed enabled the interactive search with `gsettings set org.gnome.nautilus.preferences enable-interactive-search true` and killed nautilus with `nautilus -q` and even reboot but the problem remained the same. Now, I have reinstalled Nautilus but maybe I will try that again in the future. Thank you for your reply!

**Comment by jaybosamiya** [comment] 2020-06-23 01:05
That's unfortunate :/ Sorry I was unable to help. I'm closing this issue since I am unable to reproduce on my end, but if I face the issue myself at some point, I'll reopen and dive in further.

**Closed by jaybosamiya** 2020-06-23 01:05 UTC
